DROP TABLE IF EXISTS orders, points, import_rows, accounts, audit_log;
CREATE TABLE orders (id BIGINT PRIMARY KEY, note VARCHAR(64) NOT NULL);
CREATE TABLE points (user_id BIGINT NOT NULL, amount INT NOT NULL);
CREATE TABLE import_rows (id BIGINT PRIMARY KEY, val VARCHAR(64) NOT NULL);
CREATE TABLE accounts (id BIGINT PRIMARY KEY, balance INT NOT NULL);
CREATE TABLE audit_log (id BIGINT AUTO_INCREMENT PRIMARY KEY, msg VARCHAR(128) NOT NULL);
INSERT INTO accounts VALUES (1, 100);
